config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get "/articles/archive" => "articles#archive", as: :archive

  resources :articles, only: [:index, :show]

  devise_for :admins, skip: :registrations

  scope :admins do
    get "/" => "articles#list", as: :admin_root
    get "/articles" => "articles#list", as: :admin_articles
    resources :articles, only: [:create, :update], as: :admin_article
    resources :articles, only: [:new, :edit]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  devise :database_authenticatable, :timeoutable

  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_attached_file :eye_catch,
                    :styles => { :large => "1280x720>", :medium => "854x480>", :small => "640x360>", :thumb => "426x240>" },
                    :size => { :less_than => 2.megabyte }

  validates :title, presence: true, uniqueness: true
  validates :contents, presence: true
  validates_attachment :eye_catch, presence: true,
                      content_type: { content_type: /\Aimage\/.*\z/ },
                      name: { presence: true }, size: { greater_than: 0 }

  def eye_catch_safe_path style=nil
    path = style ? eye_catch.url(style.to_sym) : eye_catch.url
    File.exist?(path[1..-1]) ? path[1..-1] : path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_admin!

  include SmartListing::Helper::ControllerExtensions
  helper SmartListing::Helper
  include ApplicationHelper

  protected
    def authenticate_admin!
      return unless is_admin?

      super
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_articles
  before_action :get_article, only: [:show, :edit, :update]

  def index
    smart_listing_create :articles, @articles, partial: "articles/articles_archive",
      default_sort: { id: "desc" }, page_sizes: [5]
  end

  def show
  end

  def archive
    smart_listing_create :articles, @articles, partial: "articles/articles_archive",
      default_sort: { id: "desc" }, page_sizes: [5, 10, 15], remote: false
  end

  def list
    smart_listing_create :articles, @articles, partial: "articles/articles_list",
      default_sort: { id: "desc" }, page_sizes: [5, 10, 15], remote: false
  end

  def new
    @article = @articles.new
  end

  def create
    @article = @articles.create article_params

    if @article.save
      render_model_success @article, "create"
      redirect_to edit_article_path(@article)
    else
      render_model_errors @article
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update article_params
      render_model_success @article, "update"
      redirect_to edit_article_path(@article)
    else
      render_model_errors @article
      render :edit
    end
  end

  private

    def article_params
      permitted = params.require(:article).permit(:eye_catch, :title, :contents)
      permitted.each do |key,val|
        permitted[key.to_sym] = ApplicationController.helpers.strip_tags(val) unless key.to_sym == :eye_catch
      end
      permitted
    end

    def get_articles
      @articles = Article.all
    end

    def get_article
      @article = @articles.find_by id: params[:id]

      not_found if @article.blank?
    end

end

app/controllers/health_controller.rb
class HealthController< ApplicationController
  #TODO implement proper health checking based on your system requirements
  def index
    render json: { status: :ok }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_admin?
    request.url["/admins"].present?
  end

  def not_found
    raise ActionController::RoutingError.new("Not Found")
  end

  def render_model_success model, action
    flash_color = case action.to_sym
      when :create
        "success"
      when :delete
        "alert"
      else
        "info"
      end
    flash[flash_color] = t("activerecord.flash.successful_#{action}",  resource: model.class.model_name.human)
  end

  def render_model_errors model
    model_class = model.class
    flash[:alert] = model.errors.map do |key, values|
      "<li><strong>#{model_class.human_attribute_name(key)}</strong> #{values}</li>"
    end.flatten.join.prepend("<ul>").concat("</ul>")
      .prepend(t("activerecord.flash.error_intro", resource: model.class.model_name.human))
  end

  def class_for flash_type
    { success: "success", error:"alert", warning: "warning", alert: "alert",
      notice: "info", notice_default:"secondary"}[flash_type.to_sym] || flash_type.to_s
  end

  def icon_for flash_type
    { success: "check", error: "alert", danger: "stop", alert: "alert",
     notice: "info",notice_default: "info"}[flash_type.to_sym] || "info"
  end

  def flash_messages opts={}
    render partial: "application/flash_messages", locals: { opts: opts }
  end

  def pagination_page_indicator smart_list, container_class, opts={}
    render partial: "smart_listing/pagination_page_custom", locals: { smart_listing: smart_list, container_classes: container_class, opts: opts }
  end

end

app/views/application/_flash_messages.html.haml
- flash.to_h.each do |msg_type, message|
  - next if ( opts.present? && flash[opts].blank? ) || msg_type == 'timedout'

  .flash{class: "callout #{class_for(msg_type)}", id: "flash-#{msg_type}", "data-closable"=>""}
    %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
      %span{"aria-hidden" => "true"} &times;
    %i.icon{class: "fi-#{icon_for(msg_type)}"}
    = message.to_s.html_safe

- flash.clear

app/views/articles/_article.html.haml
%li.archive-item
  %article.card
    = link_to article_path(article), class: "card-link" do
      = image_tag article.eye_catch_safe_path(:large), class: "card-image", alt: ""
      .card-bottom
        %h1.card-title
          = article.title
        %time.card-date{:datetime => article.created_at.strftime("%Y-%-m-%-d")}
          = article.created_at.strftime("%-d %b, %Y")

app/views/articles/_article_item.html.haml
%li.archive-item
  = link_to edit_article_path(article), class: "post-article" do
    %time.post-article-date{:datetime => article.created_at.strftime("%Y-%-m-%-d")}
      = article.created_at.strftime("%d %b, %Y")
    %h1.post-article-title
      = article.title

app/views/articles/_articles_archive.html.haml
.archive
  - if smart_listing.present?
    = pagination_page_indicator @smart_listings[:articles], "page-number" if action_name == "archive"

    %ul.archive-list
      - smart_listing.collection.each do |article|
        = render partial: "articles/article", locals: { article: article }

    = smart_listing.paginate if action_name == "archive"

  - else
    .callout
      %i.fi-clipboard-pencil
      = t("articles.not_found")

app/views/articles/_articles_list.html.haml
- if smart_listing.present?
  %ul.archive.archive-admin
    - smart_listing.collection.each do |article|
      = render partial: "articles/article_item", locals: { article: article }

  = smart_listing.paginate

- else
  .callout
    %i.fi-clipboard-pencil
    = t("articles.not_found")

app/views/articles/_form.html.haml
= form_for @article, url: @article.new_record? ? admin_articles_path : admin_article_path(@article), html: { class: :form } do |f|
  = f.label :eye_catch, "EYE CATCH IMAGE", class: "form-title"
  .form-file.u-clear
    %span#form-filename
      = @article.eye_catch.original_filename if @article.persisted? && @article.eye_catch.exists?
    %span.form-file-button UPLOAD
  = f.file_field :eye_catch, class: "input input-image", accept: "image/*"

  = f.label :title, "TITLE", class: "form-title"
  .form-body
    = f.text_field :title, class: "input input-text"

  = f.label :contents, "CONTENTS", class: "form-title"
  .form-textarea
    = f.text_area :contents, class: "input input-contents", cols: "30", rows: "10"

  - unless flash[:alert].blank?
    = flash_messages :alert

  %label.form-button{ for: :submit }
    .button
      %p.button-text Submit
  = f.submit "", id: :submit, class: "input input-submit"

  = link_to admin_articles_path, class: "form-button" do
    .button
      %p.button-text Back

app/views/articles/archive.html.haml
= smart_listing_render :articles

app/views/articles/edit.html.haml
= render partial: "articles/form"

app/views/articles/index.html.haml
= smart_listing_render :articles

- if @articles.count > 1
  = link_to archive_path, class: "archive-button" do
    .button
      %p.button-text More

app/views/articles/list.html.haml
= link_to new_article_path, class: "l-main-button" do
  .button
    %p.button-text New Article

= smart_listing_render :articles

app/views/articles/new.html.haml
= render partial: "articles/form"

app/views/articles/show.html.haml
.single
  = link_to @article.eye_catch_safe_path, target: :_blank, title: t("titles.view_original") do
    = image_tag @article.eye_catch_safe_path, class: "single-image", alt: ""
  .l-container.u-clear
    %h1.single-title
      = @article.title
    %time.single-date{:datetime => @article.created_at.strftime("%Y-%-m-%-d")}
      = @article.created_at.strftime("%-d %^b, %Y")
    %p.single-desc
      = @article.contents

    = link_to articles_path, class: "single-button" do
      .button
        %p.button-text Top

app/views/layouts/_layout.html.haml
%header{:class => "l-header js-header"}
  .l-header-top.u-clear
    .l-header-logo
      = link_to articles_path, class: :logo do
        = image_tag "logo.png", alt: "BLOG", width: "253", height: "28"

    .l-header-hamburger
      %a.hamburger.js-hamburger{:href => "#"}
        %span.hamburger-item
        %span.hamburger-item
        %span.hamburger-item

%nav.nav.js-nav
  %ul.nav-list
    %li.nav-item
      %a.nav-link{:href => articles_path} TOP
    %li.nav-item
      %a.nav-link{:href => "https://www.facebook.com/facebook/", :target => "_blank"} Facebook
    %li.nav-item
      %a.nav-link{:href => "https://twitter.com/twitter", :target => "_blank"} Twitter

.l-container.u-clear
  %main.l-main.js-main
    .l-main-block
    = yield

%footer{:class => "l-footer"}
  .l-footer-button
    %a.page-top.js-scroll{:href => "#js-body"}
      %span.page-top-arrow
  .l-footer-copyright
    %small.copyright &#169;copyright

app/views/layouts/admin/_layout.html.haml
%header{:class => "l-header l-header-admin js-header"}
  .l-header-top.u-clear
    .l-header-logo
      = link_to articles_path, class: :logo do
        = image_tag "logo-admin.png", alt: "BLOG", width: "138", height: "28"

    .l-header-text
      = link_to admin_articles_path do
        %p ADMIN PAGE

      - if admin_signed_in?
        &nbsp;
        = link_to destroy_admin_session_path, method: :delete do
          %i.fi-power{ title: "Logout" }

.l-container.u-clear
  %main.l-main.js-main
    .l-main-block
    = flash_messages if !devise_controller? && flash.present? && flash[:alert].blank?
    = yield

%footer{:class => "l-footer l-footer-admin"}
  .l-footer-copyright
    %small.copyright &#169;copyright

app/views/layouts/application.html.haml
!!! 5
%html{:lang => 'jp', :class => 'no-js', :prefix => 'og: http://ogp.me/ns#'}
  %head
    %title
      = is_admin? ? 'ADMIN PAGE' : 'LIG BLOG'

    %meta{:content => "sample text,sample tex", :name => "description"}/
    %meta{:content => "word1,word2,word3", :name => "keywords"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0", :name => "viewport"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "", :property => "og:title"}/
    %meta{:content => "sample text,sample tex", :property => "og:description"}/
    %meta{:content => "", :property => "og:url"}/
    %meta{:content => "", :property => "og:site_name"}/
    %meta{:content => "blog", :property => "og:type"}/
    %meta{:content => "", :property => "fb:admins"}/
    %meta{:content => "public/ogp.png", :property => "og:image"}/
    %meta{:content => "", :name => "apple-mobile-web-app-title"}/
    %link{:href => asset_path("common/favicon.ico"), :rel => "shortcut icon"}/
    %link{:href => asset_path("common/apple-touch-icon-precomposed.png"), :rel => "apple-touch-icon-precomposed"}/

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body#js-body

    #fb-root
    %noscript.for-no-js Javascriptを有効にしてください。
    .for-old お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。
    %input#js-base-url{:type => "hidden", :value => "./"}/

    .l-wrap.js-wrap
      = render "layouts#{is_admin? ? '/admin' : ''}/layout"

    = javascript_include_tag 'app', 'data-turbolinks-track': 'reload'

app/views/smart_listing/_action_custom.html.erb
<%# 
  Custom action.

  Available local variables:
    url
    icon
    html_options:       custom html options
-%>

<%= link_to_if(action_if, content_tag(:span, '', :class => icon, :title => title), url, html_options) %>

app/views/smart_listing/_action_delete.html.erb
<%# 
  Delete action.

  Available local variables:
    action_if:          false if action is disabled
    url:                destroy url
    icon:               icon css classes
    confirmation:       confrimation text
    title
-%>

<%= link_to_if(action_if, content_tag(:i, "", :class => icon), url, :remote => true, :class => "destroy", :method => :delete, :title => title || t("smart_listing.actions.destroy"), :data => {:confirmation => confirmation || t("smart_listing.msgs.destroy_confirmation")} ) %>

app/views/smart_listing/_action_edit.html.erb
<%# 
  Edit action.

  Available local variables:
    action_if:          false if action is disabled
    url:                edit url
    icon:               icon css classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :remote => true, :class => "edit", :title => title || t("smart_listing.actions.edit") ) %>

app/views/smart_listing/_action_show.html.erb
<%# 
  Show action.

  Available local variables:
    action_if:          false if action is disabled
    url:                show url
    icon:               icon clss classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :class => "show", :title => title || t("smart_listing.actions.show") ) %>

app/views/smart_listing/_item_new.html.erb
<%# 
  New list item element (contains new item placeholder and add button).

  Available local variables:
    placeholder_classes:      classes for the main container
    new_item_action_classes:  new item action classes
    colspan              
    no_items_classes:         no items container classes
    no_items_text:            no items text displayed inside container
    new_item_button_url:      argument to link_to (new item button)
    new_item_button_classes
    new_item_button_text
    new_item_autoshow         automatically show new item placeholder
    new_item_content          new item placeholder content (usually some form)
-%>

<%= content_tag(:tr, '', :class => placeholder_classes + %w{info}, :data => {smart_listing_config.data_attributes(:autoshow) => new_item_autoshow}) do %>
  <%= new_item_content %>
<% end %>
<%= content_tag(:tr, :class => new_item_action_classes + %w{info}) do %>
  <%= content_tag(:td, :colspan => colspan) do %>
    <%= content_tag(:p, :class => no_items_classes + %w{pull-left}) do %>
      <%= no_items_text %>
    <% end %>
    <%= link_to(new_item_button_url, :remote => true, :class => new_item_button_classes + %w{btn pull-right}) do %>
      <%= content_tag(:i, '', :class => smart_listing_config.classes(:icon_new)) %>
      <%= new_item_button_text %>
    <% end %>
  <% end %>
<% end %>

app/views/smart_listing/_pagination_page_custom.html.haml
-# Custom Pagination page indicator.

-# Available local variables:
-#   container_classes:  classes for the main container
-#   smart_listing:      current SmartListing instance

= content_tag :div, class: container_classes do
  - if smart_listing.options[:paginate]
    = t('views.pagination.page')
    = content_tag :span do
      = smart_listing.collection.current_page
      \/
      = smart_listing.collection.total_pages

app/views/smart_listing/_pagination_per_page_link.html.haml
-# Pagination single per-page link.

-# Available local variables:
-#   page:           page number
-#   url:            page url (if page is not selected)
-#   smart_listing:  current SmartListing instance
-#   builder:        current builder instance

- name = page == 0 ? t('views.pagination.unlimited') : page
= url ? link_to(name, url, :remote => smart_listing.remote?) : content_tag(:span, name)

app/views/smart_listing/_pagination_per_page_links.html.haml
-# Pagination per-page links.

-# Available local variables:
-#   container_classes:  classes for the main container
-#   per_page_sizes:     array of available per-page sizes
-#   smart_listing:      current SmartListing instance
-#   builder:            current builder instance

= content_tag(:div, :class => container_classes) do
  - if smart_listing.options[:paginate] && (smart_listing.count > smart_listing.page_sizes.first)
    = t('views.pagination.per_page')
    - per_page_sizes.each do |p|
      = builder.pagination_per_page_link p
      - break if p >= smart_listing.count
    |
  = t('views.pagination.total')
  = content_tag(:span, smart_listing.count, :class => "count")

app/views/smart_listing/_sortable.html.erb
<%# 
  Sortable attribute listing header.

  Available local variables:
    container_classes:  classes for the main container
    url:                sortable link url
    attribute:          current attribute name
    title:              current attribute title
    order:              defines column sort order
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= link_to url, :class => container_classes, :data => {:attr => attribute}, :remote => true do %>
  <%= title %>
  <% if order %>
    <span class="<%= order == "asc" ? smart_listing_config.classes(:icon_sort_up) : smart_listing_config.classes(:icon_sort_down) %>"></span>
  <% else %>
    <span class="<%= smart_listing_config.classes(:icon_sort_none) %>"></span>
  <% end %>
<% end %>